import { Box } from "@mui/material";
import type { Metadata } from "next";
import { getLocale } from "next-intl/server";
import Footer from "./components/layout/footer";
import Header from "./components/layout/header";
import Main from "./components/layout/main";
import I18nClientProvider from "./components/providers/i18n-client-provider";
import MuiThemeProvider from "./components/providers/mui-theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body>
        <I18nClientProvider>
          <MuiThemeProvider>
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                minHeight: "100vh",
              }}
            >
              <Header />
              <Main>{children}</Main>
              <Footer />
            </Box>
          </MuiThemeProvider>
        </I18nClientProvider>
      </body>
    </html>
  );
}
