import { Box } from "@mui/material";
import type { Metadata } from "next";
import { getLocale } from "next-intl/server";
import Footer from "./components/layout/footer";
import Header from "./components/layout/header";
import Main from "./components/layout/main";
import Providers from "./components/providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body>
        <Providers>
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              minHeight: "100vh",
            }}
          >
            <Header />
            <Main>{children}</Main>
            <Footer />
          </Box>
        </Providers>
      </body>
    </html>
  );
}
